apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-test3
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/demo-test3/overlays/development
    repoURL: https://github.com/flacatus/demo-test3-gitops
    targetRevision: main
  destination:
    namespace: demo-test3
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
