apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-test3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-test3 
  name: demo-test3
  namespace: demo-test3
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-test3
    weight: 100 
