apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-test3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-test3 
  name: demo-test3
  namespace: demo-test3
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: demo-test3 
